### ISSUE TITLE
When will you update to support statamic 5?

### ISSUE THREAD

**Issue by paulpreibisch** [lucky-media/landtamic#35]
Hi there, 

Very interested in your addon.  I just installed statamic 5, when will you have a version to support this?

**Comment by lokmanm** [comment]
Hey @paulpreibisch,

Landtamic works with Statamic 5. 

Thanks!

**Comment by paulpreibisch** [comment]
thanks, by the way, anyway I can try before buy?

**Comment by lokmanm** [comment]
@paulpreibisch sadly that's not on us. Statamic handles Starter Kits differently from addons. You can read the differences [here](https://statamic.dev/starter-kits/creating-a-starter-kit#addons-vs-starter-kits).

**Comment by Hesesses** [comment]
Just wanted to let you know that it says "Note that you will need to be running Statamic 4.x."

here: https://statamic.com/starter-kits/luckymedia/landtamic

<img width="793" alt="image" src="https://github.com/user-attachments/assets/991f5f09-ec82-4f2e-b2e2-62292e333311">
