### ISSUE TITLE
Error Asset container has not be configured

### ISSUE THREAD

**Issue by that0n3guy** [lucky-media/landtamic#7]
In the blueprint there are several asset fieldtypes that are missing `container: assets` in the yaml.

This will cause a bug if another asset is added:
![image](https://user-images.githubusercontent.com/113870/154528902-0c8870f2-0613-4802-bf23-046fc7cdc880.png)

It's not hard to fix, but there are quite a few of them and takes time.

**Comment by lokmanm** [comment]
This issue was fixed with the latest release of v1.1.

Thanks again for reporting.
